version: "3"
services:
  mongodb:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD-Aaa12345}
    command: mongod --port 27017 --bind_ip_all
    restart: always

  mongo-seed:
    image: mongo:3.6
    command: bash -c
             "mongoimport --host mongodb --username '${DB_USER-root}' --password '${DB_PASSWORD-Aaa12345}' --authenticationDatabase admin --db test --collection roles --type json --file /roles.json --jsonArray &&
              mongoimport --host mongodb --username '${DB_USER-root}' --password '${DB_PASSWORD-Aaa12345}' --authenticationDatabase admin --db test --collection users --type json --file /users.json --jsonArray"
    volumes:
      - ./mongo-seed/roles.json:/roles.json
      - ./mongo-seed/users.json:/users.json
    depends_on:
      - mongodb
    restart: on-failure

  server:
    build: ./hox-server
    environment:
      DB_URL: mongodb:27017
      DB_USER: ${DB_USER-root}
      DB_PASSWORD: ${DB_PASSWORD-Aaa12345}
      DB_AUTH : admin
      DB_USE_SSL: 'false'
      API_PORT: 4000
      JWT_EXPIRY: ${JWT_EXPIRY-86400}
      JWT_RANDOMIZE_SECRET: 'true'
      JWT_SECRET: ${JWT_SECRET-5uper5ecretJW7}
    depends_on:
      - mongo-seed
    restart: always

  client:
    build: ./hox-client
    environment:
      LE_DOMAIN: ${LE_DOMAIN-selfsigned}
    depends_on:
      - server
    restart: always

  certproxy:
    build: ./certproxy
    environment:
      LE_DOMAIN: ${LE_DOMAIN-selfsigned}
      LE_EMAIL: ${LE_EMAIL}
      LE_ENVIRONMENT: ${LE_ENVIRONMENT-staging}
      CB_PORT: ${CB_PORT-8080}
    ports:
      - '80:80'
    volumes:
      - ssl:/etc/ssl
    depends_on:
      - client
    restart: always

  reverseproxy:
    build: ./reverseproxy
    environment:
      LE_DOMAIN: ${LE_DOMAIN-selfsigned}
    ports:
      - '443:443'
      - '4000:4000'
      - '27017:27017'
    volumes:
      - ssl:/etc/ssl
    depends_on:
      - certproxy
    restart: always

  api-seed:
    build:
      context: ./api-seed
      args:
        GIT_COMMIT: ${GIT_COMMIT-dev}
    environment:
      API_URL: http://server:4000/api/
      API_USERNAME: admin1
      API_PASSWORD: ${ADMIN_USER_PASSWORD-admin1}
      INVITE_ONLY: ${INVITE_ONLY-false}
      IMPORT_FILES: ${IMPORT_FILES-hoxInstruments}
    depends_on:
      - reverseproxy
    restart: on-failure

volumes:
  ssl:
