version: "2"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    command: mongod --port 27017 --bind_ip_all

  mongo-seed:
    image: mongo:latest
    command: bash -c
             "mongoimport --host mongodb --username $DB_USER --password $DB_PASSWORD --authenticationDatabase admin --db test --collection roles --type json --file /roles.json --jsonArray &&
              mongoimport --host mongodb --username $DB_USER --password $DB_PASSWORD --authenticationDatabase admin --db test --collection users --type json --file /users.json --jsonArray"
    volumes:
      - ./mongo-seed/roles.json:/roles.json
      - ./mongo-seed/users.json:/users.json
    depends_on:
      - mongodb

  server:
    restart: always
    build: ./hox-server
    environment:
      PORT: 4000
      DATABASE: mongodb:27017
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_AUTH: admin
    depends_on:
      - mongo-seed

  client:
    build: ./hox-client
    depends_on:
      - server

  openssl:
    build:
      context: ./openssl
      args:
        - COMMON_NAME=Hox Trader
        - KEY_NAME=hoxtrader
    volumes:
      - certs:/certs
    depends_on:
      - client
  reverseproxy:
    build: ./reverseproxy
    ports:
      - '80:80'
      - '443:443'
      - '4200:4200'
      - '27017:27017'
    volumes:
      - certs:/etc/ssl/certs
    restart: always
    depends_on:
      - openssl
volumes:
  certs:
